const express = require('express')
const Router = express.Router()
const { getToateProgramarile, getProgramarileMele, adaugaComentariu, modificaStatus, adaugaProgramare } = require('../src/Programari')
const { register, login, getUsers } = require('../src/Users')
const { getPersonal, adaugaDoctor, eliminareDoctor } = require('../src/Personal')
const { getIstoricDoctori } = require('../src/Istoric')
const { getServicii } = require('../src/Servicii')
const { getSpecializari, getPreturi, adaugaServiciu } = require('../src/Specializari')
const { getOreDisponibile } = require('../src/Programari')

Router.get('/toate-programarile', getToateProgramarile)
Router.post('/login', login)
Router.get('/personal', getPersonal)
Router.get('/users', getUsers)
Router.get('/specializari', getSpecializari)
Router.get('/preturi', getPreturi)
Router.get('/programarile-mele', getProgramarileMele)
Router.get('/istoric-doctori', getIstoricDoctori)
Router.get('/servicii', getServicii)
Router.get('/ore-disponibile', getOreDisponibile)
Router.post('/adauga-comentariu', adaugaComentariu)
Router.post('/modifica-status', modificaStatus)
Router.post('/programare', adaugaProgramare)
Router.put('/register', register)
Router.put('/adauga-doctor', adaugaDoctor)
Router.delete('/eliminare-doctor', eliminareDoctor)
Router.put('/adauga-serviciu', adaugaServiciu)

module.exports = Router

